watchdog:
  ros__parameters:
    # FL, FR, RL, RR
    q_max: [ 1.047, 3.490, -0.837,
             1.047, 3.490, -0.837,
             1.047, 4.537, -0.837,
             1.047, 4.537, -0.837]
    q_min: [ -1.047, -1.570, -2.84,
             -1.047, -1.570, -2.84,
             -1.047, -0.523, -2.84,
             -1.047, -0.523, -2.84]
        # Extracted from go2_description urdf
    margin_duration: [0.06, 0.06, 0.06,
                      0.06, 0.06, 0.06,
                      0.06, 0.06, 0.06,
                      0.06, 0.06, 0.06]
        # See https://github.com/inria-paris-robotics-lab/go2_control_interface/issues/11#issuecomment-2995477021