watchdog:
  ros__parameters:
    # FL, FR, RL, RR
    q_max: [0.7, 2.5, -0.9,
            0.7, 2.5, -0.9, #
            0.7, 3.5, -0.9,
            0.6, 3.5, -0.9] #
    q_min: [-0.7, -1.5, -2.6,
            -0.7, -1.5, -2.6, #
            -0.6, -0.5, -2.6,
            -0.7, -0.5, -2.6] #
    dq_max: 80.0
