watchdog:
  ros__parameters:
    # FL, FR, RL, RR
    q_max: [0.5, 1.6, -0.9,
            0.4, 1.6, -0.9,
            0.7, 1.6, -0.9,
            0.6, 1.6, -0.9]
    q_min: [-0.4, 0., -2.8,
            -0.5, 0., -2.8,
            -0.6, 0., -2.8,
            -0.7, 0., -2.8]
    v_max: 30.0
